# Generated by Django 5.2.3 on 2025-06-11 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('specs', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.company')),
            ],
        ),
    ]
